name: obx_rag_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  langchain: ^0.7.7+1
  langchain_community: ^0.3.2+2
  langchain_ollama: ^0.3.2+1
  objectbox: ^4.0.3
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  objectbox_generator: any

flutter:
  uses-material-design: true
